# Brewfile — minimal external dependencies for gomoku-rust-httpd.
#
# The Rust toolchain is the one strictly required dependency. The other
# entries are quality-of-life tools wired into the justfile and lefthook.
#
# Usage:
#   brew bundle install
#
# Note: install Rust via rustup (https://rustup.rs/) for the most up-to-date
# toolchain rather than `brew install rust`. We pin only the helpers below.

# Task runner used by ./justfile.
brew "just"

# Pre-commit / pre-push hook driver.
brew "lefthook"

# Required by the integration test for parsing JSON results.
brew "python@3"

# HTTP client used in the smoke-test recipes inside justfile.
brew "curl"

# ─── Format / check tooling ──────────────────────────────────────────────────
# Used by `just/justfile.format` (format-* and check-* recipes).

# C / C++ formatter (used for gomoku-c/src and gomoku-c/tests).
brew "clang-format"

# Shell script formatter (used to format anything with a #!/bin/bash shebang).
brew "shfmt"

# Prettier — TS/JS/JSON/CSS/Markdown formatter (frontend + markdown).
brew "prettier"

# Ruby 
brew "rubyfmt"

# Python
brew "ruff"

# ─── Gomocup submission tooling ──────────────────────────────────────────────

# Cross-compilers for the Gomocup Win32/Win64 brain submission.
# Used by `just gomocup` via `make -C gomoku-c gomocup-win`.
brew "mingw-w64"

# `zip` ships with macOS but we list it for non-Mac runners that install
# via `brew bundle`. Used by `make -C gomoku-c gomocup-zip`.
brew "zip"

# ─── Rust Based Utilities ──────────────────────────────────────────────


brew 'bash'
brew 'bat'
brew 'btop'
brew 'codespell'
brew 'curl'
brew 'direnv'
brew 'dua'
brew 'dysk'
brew 'eza'
brew 'fd'
brew 'jq'
brew 'just'
brew 'lefthook'
brew 'mdformat'
brew 'mdfried'
brew 'mprocs'
brew 'postgresql@{{PGVERSION}}'
brew 'prettier'
brew 'procs'
brew 'ripgrep'
brew 'shellcheck'
brew 'shfmt'
brew 'uv'

tap 'homebrew/bundle'
tap 'homebrew/services'

# Build Environment/C/C++
brew 'ack'
brew 'adns'
brew 'asciidoc'
brew 'asciidoctor'
brew 'autoconf'
brew 'automake'
brew 'aws-iam-authenticator'
brew 'aws-vault'
brew 'awscli'
brew 'bash-completion@2'
brew 'bash'
brew 'bat'
brew 'bats-assert'
brew 'bats-core'
brew 'bats-file'
brew 'bats-support'
brew 'cloc'
brew 'cmake'
brew 'colordiff'
brew 'coreutils'
brew 'curl'
brew 'direnv'
brew 'fish'
brew 'fontconfig'
brew 'freetype'
brew 'fzf'
brew 'gawk'
brew 'gcc'
brew 'gd'
brew 'gdbm'
brew 'geoip'
brew 'gettext'
brew 'gh'
brew 'ghostscript'
brew 'git'
brew 'glances'
brew 'glib'
brew 'gmp'
brew 'gnu-getopt'
brew 'gnu-indent'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'gnu-time'
brew 'gnu-which'
brew 'gnupg'
brew 'gnutls'
brew 'go'
brew 'gobject-introspection'
brew 'golangci-lint'
brew 'gpg2'
brew 'graphicsmagick'
brew 'graphite2'
brew 'graphviz'
brew 'gts'
brew 'guile'
brew 'haproxy'
brew 'harfbuzz'
brew 'haskell-stack'
brew 'helm'
brew 'htop'
brew 'icu4c'
brew 'ilmbase'
brew 'imagemagick'
brew 'isl'
brew 'jasper'
brew 'jemalloc'
brew 'jp2a'
brew 'jpeg'
brew 'jq'
brew 'krb5'
brew 'kubernetes-cli'
brew 'lame'
brew 'libassuan'
brew 'libde265'
brew 'libevent'
brew 'libffi'
brew 'libgcrypt'
brew 'libgpg-error'
brew 'libheif'
brew 'libiconv'
brew 'libidn2'
brew 'libksba'
brew 'liblqr'
brew 'libmemcached'
brew 'libmpc'
brew 'libomp'
brew 'libpng'
brew 'libpq'
brew 'libssh2'
brew 'libtasn1'
brew 'libtiff'
brew 'libtool'
brew 'libunistring'
brew 'libusb'
brew 'libxml2'
brew 'libxslt'
brew 'libyaml'
brew 'libzip'
brew 'little-cms2'
brew 'lua'
brew 'lz4'
brew 'lzo'
brew 'make'
brew 'maven-completion'
brew 'maven-shell'
brew 'maven'
brew 'memcached'
brew 'minikube'
brew 'mpfr'
brew 'ncurses'
brew 'ndiff'
brew 'netcat'
brew 'netpbm'
brew 'nettle'
brew 'nginx'
brew 'nmap'
brew 'node'
brew 'npth'
brew 'oniguruma'
brew 'oxker'
brew 'openexr'
brew 'openssl'
brew 'p11-kit'
brew 'p7zip'
brew 'pandoc'
brew 'pango'
brew 'parallel'
brew 'pcre'
brew 'pcre2'
brew 'perl'
brew 'pg_top'
brew 'pinentry'
brew 'pixman'
brew 'pkg-config'
brew 'popt'
brew 'postgresql'
brew 'pstree'
brew 'pyenv'
brew 'pygments'
brew 'rbenv'
brew 'readline'
brew 'redis'
brew 'ripgrep'
brew 'rsync'
brew 'ruby-build'
brew 'ruby-completion'
brew 'ruby'
brew 'rust'
brew 'rustup-init'
brew 'rustup'
brew 'shared-mime-info'
brew 'shellcheck'
brew 'source-highlight'
brew 'spaceman-diff'
brew 'sqlite'
brew 'stripe-cli'
brew 'stripe-mock'
brew 'the_silver_searcher'
brew 'tree'
brew 'typescript'
brew 'unar'
brew 'unbound'
brew 'v8'
brew 'vim'
brew 'volta'
brew 'watch'
brew 'wdiff'
brew 'webp'
brew 'wget'
brew 'x265'
brew 'xmlto'
brew 'xxhash'
brew 'xz'
brew 'yamlfmt'
brew 'yamllint'
brew 'yarn'
brew 'ydiff'
brew 'yq'
brew 'zlib'
brew 'zstd'

cask 'chromedriver'

cask 'font-andale-mono'
cask 'font-anonymice-powerline'
cask 'font-arvo'
cask 'font-aurulent-sans-mono-nerd-font'
cask 'font-awesome-terminal-fonts'
cask 'font-bitstream-vera-sans-mono-nerd-font'
cask 'font-blex-mono-nerd-font'
cask 'font-cairo'
cask 'font-cascadia-mono'
cask 'font-consolas-for-powerline'
cask 'font-cousine'
cask 'font-cutive-mono'
cask 'font-d2coding'
cask 'font-dejavu-sans-mono-for-powerline'
cask 'font-everson-mono'
cask 'font-fantasque-sans-mono'
cask 'font-fontawesome'
cask 'font-ia-writer-mono'
cask 'font-inconsolata'
cask 'font-jetbrains-mono'
cask 'font-kawkab-mono'
cask 'font-lekton-nerd-font'
cask 'font-menlo-for-powerline'
cask 'font-meslo-for-powerline'
cask 'font-miriam-mono-clm'
cask 'font-monoid'
cask 'font-monoisome'
cask 'font-mononoki'
cask 'font-monoton'
cask 'font-noto-mono'
cask 'font-oswald'
cask 'font-oxygen'
cask 'font-oxygen-mono'
cask 'font-powerline-symbols'
cask 'font-pt-mono'
cask 'font-roboto'
cask 'font-roboto-mono-nerd-font'
cask 'font-share-tech-mono'
cask 'font-sometype-mono'
cask 'font-ubuntu'
cask 'font-victor-mono'
