# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.13"
  gem "rspec-its", "~> 2.0"
  gem "rubocop", "~> 1.60", require: false
  gem "simplecov", "~> 0.22", require: false
  gem "webmock", "~> 3.20"
end
